### ISSUE TITLE
The template variables look like they're getting messed up

### ISSUE THREAD

**Issue by kalenjordan** [magento-hackathon/Responsive-Email-Templates-with-CSS-Inliner#2]
It looks like the template variables (ex: `{{var logo_url}}`) might be getting converted to html entities by the html in-lining, before the template variables are parsed and injected.

**Comment by avstudnitz** [comment]
You're right, that might be a problem. I didn't think about that. If we want to inline after the variables get replaced, we have to look for a different approach.

**Comment by kalenjordan** [comment]
I was thinking maybe we just hack it and after the inlining replace all of the `{` and `}` html entities with the regular characters.

If not that, then we just go back to a simple rewrite of the email template module.

**Comment by kalenjordan** [comment]
It must have been the other inliner (InlineStyle) that I had tried which caused problems.  I just tested this again with our original (and current) inliner TijsVerkoyen_CssToInlineStyles and it works fine.

**Comment by kalenjordan** [comment]
Actually, it's the {{var logo_url}} specifically inside of `<img src="...">` which causes a problem.  It must have some logic that converts things to html entities if they are inside quotes.

Back to my hack :)

**Comment by kalenjordan** [comment]
Okay so the inliner seems to be url encoding template variables inside of `<img src="...">` so I added some logic to undo that.
