### ISSUE TITLE
Recursion

### ISSUE THREAD

**Issue by thaiphan** [magento-hackathon/Responsive-Email-Templates-with-CSS-Inliner#5]
I noticed that `Hackathon_ResponsiveEmail_Model_Email_Template` extends `Hackathon_ResponsiveEmail_Model_Email_Template_Abstract` which can also potentially extend `Hackathon_ResponsiveEmail_Model_Email_Template`. Just a heads up!

**Comment by kalenjordan** [comment]
Oops!  You should be able to safely just remove lines 7 and 8:
https://github.com/magento-hackathon/Responsive-Email-Templates-with-CSS-Inliner/blob/master/app/code/community/Hackathon/ResponsiveEmail/Model/Email/Template/Abstract.php#L7

I think I didn't catch that b/c I have the other modules installed in my test environment.  Also I'm not really actively using this - I merged this code into another project that I've been working on - but feel free to make any modifications / PRs that you'd like to.
